// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPUpPHJfcId_zEzeOtc-D3kEUIxqz3DJo',
    appId: '1:149609852776:web:15590b63f35f8e3ae030dd',
    messagingSenderId: '149609852776',
    projectId: 'opticart-c847b',
    authDomain: 'opticart-c847b.firebaseapp.com',
    storageBucket: 'opticart-c847b.firebasestorage.app',
    measurementId: 'G-M42TVMV14G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz9zRX2cGRWJGKFpO-W_QVXWUDj40Ff-c',
    appId: '1:149609852776:android:1a130d2671d161b7e030dd',
    messagingSenderId: '149609852776',
    projectId: 'opticart-c847b',
    storageBucket: 'opticart-c847b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2mCPCiQmKkkNTWfGYS9ZGkNEHZrYGfP0',
    appId: '1:149609852776:ios:3a0c8da7776b7a1de030dd',
    messagingSenderId: '149609852776',
    projectId: 'opticart-c847b',
    storageBucket: 'opticart-c847b.firebasestorage.app',
    iosBundleId: 'com.example.opticart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2mCPCiQmKkkNTWfGYS9ZGkNEHZrYGfP0',
    appId: '1:149609852776:ios:3a0c8da7776b7a1de030dd',
    messagingSenderId: '149609852776',
    projectId: 'opticart-c847b',
    storageBucket: 'opticart-c847b.firebasestorage.app',
    iosBundleId: 'com.example.opticart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPUpPHJfcId_zEzeOtc-D3kEUIxqz3DJo',
    appId: '1:149609852776:web:da29b126bf86e5e2e030dd',
    messagingSenderId: '149609852776',
    projectId: 'opticart-c847b',
    authDomain: 'opticart-c847b.firebaseapp.com',
    storageBucket: 'opticart-c847b.firebasestorage.app',
    measurementId: 'G-DQT0HVTMET',
  );
}
