import 'package:dio/dio.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:flutter/foundation.dart'; // For debugPrint
import '../domain/product.dart';

class SerpApiService {
  final Dio _dio = Dio();
  final String _baseUrl = 'https://serpapi.com/search';

  /// Searches for products using a text query (generated by Gemini).
  /// Uses Google Shopping engine for accurate pricing and detection.
  Future<List<Product>> searchByQuery(String query) async {
    try {
      final String? apiKey = dotenv.env['SERPAPI_KEY'];
      if (apiKey == null || apiKey.isEmpty) {
        throw Exception('SerpApi key not found in .env');
      }

      debugPrint('Searching Google Shopping for: $query');

      final response = await _dio.get(
        _baseUrl,
        queryParameters: {
          'engine': 'google_shopping', // Switch to Shopping Engine
          'api_key': apiKey,
          'q': query,
          'hl': 'zh-TW',
          'gl': 'tw', // Location: Taiwan
          'location': 'Taiwan',
          'google_domain': 'google.com.tw',
        },
      );

      debugPrint('SerpApi Response Status: ${response.statusCode}'); 
      
      if (response.statusCode == 200) {
        final data = response.data;
        return _parseShoppingResponse(data);
      } else {
        throw Exception('Failed to load search results: ${response.statusCode}');
      }
    } catch (e) {
      debugPrint('SerpApi Error: $e'); 
      throw Exception('SerpApi Error: $e');
    }
  }

  List<Product> _parseShoppingResponse(Map<String, dynamic> data) {
    final List<Product> products = [];
    
    if (data['shopping_results'] != null) {
      final results = data['shopping_results'] as List;
      debugPrint('Found ${results.length} shopping results'); 

      for (var item in results) {
        try {
          final title = item['title'] ?? 'Unknown Product';
          final thumbnail = item['thumbnail'] ?? '';
          // Fallback for different key names
          final link = item['link'] ?? item['product_link'] ?? '';
          final source = item['source'] ?? (item['merchant'] != null ? item['merchant']['name'] : 'Google Shopping');
          
          double price = 0.0;
          String currency = 'TWD';
          
          if (item['price'] != null) {
             String priceStr = item['price'].toString();
             if (priceStr.contains('TWD') || priceStr.contains('NT\$')) {
               currency = 'TWD';
             }
             priceStr = priceStr.replaceAll(RegExp(r'[^0-9.]'), '');
             price = double.tryParse(priceStr) ?? 0.0;
          }
          
          // Fallback extracted_price check
          if (price == 0.0 && item['extracted_price'] != null) {
             price = (item['extracted_price'] as num).toDouble();
          }

          if (title.isNotEmpty && link.isNotEmpty) {
            products.add(Product(
              id: item['product_id'] ?? link.hashCode.toString(),
              name: title,
              price: price,
              currency: currency,
              imageUrl: thumbnail,
              platform: source.toString(),
              productUrl: link,
            ));
            // debugPrint('✅ Added product: $title ($price)');
          } else {
             debugPrint('⚠️ Skipped item: Title="$title", Link="$link"');
          }
        } catch (e) {
          debugPrint('❌ Error parsing item: $e');
          continue;
        }
      }
    } else {
      debugPrint('No shopping_results found in response');
    }
    
    return products;
  }
}
